language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - TEST_APP_CONFIG=Debug
  - TEST_APP_CONFIG=Release

matrix:
  exclude:
  - os: osx
    compiler: gcc

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.8.0-Linux-x86_64/bin:$PATH                                       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then wget --no-check-certificate http://cmake.org/files/v3.8/cmake-3.8.0-Darwin-x86_64.tar.gz  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then tar -xzf cmake-3.8.0-Darwin-x86_64.tar.gz                                                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then export PATH=$PWD/cmake-3.8.0-Darwin-x86_64/CMake.app/Contents/bin:$PATH                   ;fi


script:
  - mkdir build_$TEST_APP_CONFIG
  - cd build_$TEST_APP_CONFIG
  - cmake ..
  - cmake --build . --config $TEST_APP_CONFIG